### ISSUE TITLE
Migrate to manifest v3

### ISSUE THREAD

**Issue by ghost** [matt-kruse/talk-time#5]
Manifest V2 is set to be end-of-lifed.  The key dates (at time of this writing):

January 2023:
* Chrome stops running Manifest V2 extensions
* Chrome Web Store stops accepting updates to existing Manifest V2 extensions
* There is a carveout for enterprises that can allow manifest V2 extensions in their organization

June 2023:
* Manifest V2 extensions no longer function in Chrome even with the use of enterprise policy

https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/

Helpful migration links:
* https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/
* https://developer.chrome.com/docs/extensions/mv3/mv3-migration-checklist/

**Comment by tvd98point6** [comment]
I started on this here: https://github.com/matt-kruse/talk-time/compare/main...tvd98point6:manifest-v3

I'll give a couple days for https://github.com/matt-kruse/talk-time/pull/4 to be reviewed before putting up the v3 changes.

**Comment by natbaca** [comment]
Hello - 
@matt-kruse it appears the current live version of the extension, https://chromewebstore.google.com/detail/talk-time-for-google-meet/bonlpfoeaoeadalicohkefgpkjplmfbg?hl=en-US , still has version 3.1 and is thus missing this fix. As a consequence, following Google's recent final phase of this deprecation, this extension has been disabled. 

Would you be able to update the store listing to be v3.2 / main? I know you can bypass this in various ways (and I've done this locally), but more people could access this extension if the version were updated! 

Thanks, and thanks again for this great extension!
